### ISSUE TITLE
Could you kindly upload the input data?

### ISSUE THREAD

**Issue by Jwenyi** [thomasmooon/leoss-cov19#1]
Hi Thomas,
Apologize for disturbing you.

I found your paper is of great interesting. But I'm really new to deep learning, I'd like to learn your codes of `deepsurv_nCV_arrayjob.py` to enable me to process the same analysis in my study. However, I could not take a look in the structure of input data due to  `leoss_decoded.pkl` and `data_items.txt` missed. I would be very grateful if you could upload or send me these files.

Best regards,
Wenyi Jin

**Comment by thomasmooon** [comment]
Dear Wenyi,

the LEOSS data is not publicly available, sharing is not permitted. Access is only granted to authorized users / organizations upon request and approval through https://leoss.net/.

Best
Thomas
